<<<<<<< HEAD
#High Score Data
#Tue Jul 07 17:45:25 JST 2026
stage1=11920
=======
#High Score Data
#Wed Jul 08 09:15:58 JST 2026
stage1=7380
>>>>>>> branch 'master' of https://github.com/hayakawa-rai/GameApplication.git
stage2=7160
stage3=5480
